"""Build the MiniPal SolidWorks model set.

The script creates a small SolidWorks project under
``mechanical/solidworks_minipal``:

- individual simplified SLDPRT files for the shell and each module
- sub-assemblies for the electronics and actuator groups
- one top-level assembly that integrates the complete desk robot
- a STEP export of the final assembly, when the local SolidWorks export
  options allow it

Coordinates are in millimeters in the layout dictionaries and converted to
meters for the SolidWorks API.
"""

from __future__ import annotations

import os
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import pythoncom
import win32com.client
from win32com.client import VARIANT


ROOT = Path(__file__).resolve().parents[2]
PROJECT_DIR = ROOT / "mechanical" / "solidworks_minipal"
PARTS_DIR = PROJECT_DIR / "parts"
ASSEMBLY_DIR = PROJECT_DIR / "assemblies"
EXPORT_DIR = PROJECT_DIR / "exports"

MM = 0.001

SW_DOC_PART = 1
SW_DOC_ASSEMBLY = 2
SW_OPEN_SILENT = 1
SW_SAVE_CURRENT_VERSION = 0
SW_SAVE_SILENT = 1
SW_THIS_CONFIGURATION = 1
SW_ADD_CURRENT_SELECTED_CONFIG = 0
SW_START_SKETCH_PLANE = 0
SW_START_OFFSET = 3
SW_END_BLIND = 0

FRONT_PLANE = "\u524d\u89c6\u57fa\u51c6\u9762"
TOP_PLANE = "\u4e0a\u89c6\u57fa\u51c6\u9762"


@dataclass(frozen=True)
class Color:
    r: float
    g: float
    b: float
    ambient: float = 0.45
    diffuse: float = 0.85
    specular: float = 0.25
    shininess: float = 0.25
    transparency: float = 0.0
    emission: float = 0.0

    def as_variant(self) -> VARIANT:
        values = [
            self.r,
            self.g,
            self.b,
            self.ambient,
            self.diffuse,
            self.specular,
            self.shininess,
            self.transparency,
            self.emission,
        ]
        return VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_R8, values)


COLORS = {
    "shell": Color(0.86, 0.93, 0.96, transparency=0.55),
    "shell_edge": Color(0.68, 0.79, 0.85, transparency=0.35),
    "mount": Color(0.42, 0.48, 0.55, transparency=0.15),
    "sensor_board": Color(0.08, 0.48, 0.38),
    "sensor_eye": Color(0.78, 0.82, 0.86, specular=0.6, shininess=0.55),
    "servo": Color(0.12, 0.34, 0.80),
    "servo_horn": Color(0.96, 0.96, 0.90),
    "esp32": Color(0.08, 0.50, 0.78),
    "module": Color(0.05, 0.12, 0.22),
    "pin": Color(0.93, 0.76, 0.24),
    "battery": Color(0.13, 0.68, 0.36),
    "button": Color(0.94, 0.25, 0.20),
    "led": Color(0.82, 0.20, 0.72, specular=0.55, shininess=0.45),
    "buzzer": Color(0.10, 0.10, 0.11),
    "label": Color(1.0, 0.92, 0.18),
    "wire": Color(0.02, 0.02, 0.025),
    "trim": Color(0.95, 0.57, 0.22, transparency=0.05),
    "rubber": Color(0.03, 0.03, 0.035),
    "clear": Color(0.70, 0.90, 1.0, transparency=0.65),
    "sim_body": Color(0.93, 0.96, 0.98),
    "sim_head": Color(0.96, 0.98, 1.0),
    "sim_shadow": Color(0.58, 0.66, 0.74),
    "sim_window": Color(0.72, 0.83, 0.91, transparency=0.10),
    "sim_eye_blue": Color(0.05, 0.28, 0.52, specular=0.45, shininess=0.45),
    "sim_eye_ring": Color(0.76, 0.82, 0.88),
    "sim_led_blue": Color(0.04, 0.36, 0.70, specular=0.5, shininess=0.45),
}


def m(value_mm: float) -> float:
    return value_mm * MM


def connect_solidworks():
    try:
        sw = win32com.client.Dispatch("SldWorks.Application")
    except Exception as exc:  # pragma: no cover - depends on local COM state
        raise RuntimeError(
            "Could not connect to SolidWorks through COM. Open SolidWorks once "
            "and rerun this script."
        ) from exc
    sw.Visible = True
    return sw


def ensure_dirs(clean: bool = True) -> None:
    if clean and PROJECT_DIR.exists():
        # This directory is generated by this script; remove only this exact path.
        shutil.rmtree(PROJECT_DIR)
    PARTS_DIR.mkdir(parents=True, exist_ok=True)
    ASSEMBLY_DIR.mkdir(parents=True, exist_ok=True)
    EXPORT_DIR.mkdir(parents=True, exist_ok=True)


def new_part(sw):
    template = sw.GetUserPreferenceStringValue(8)
    model = sw.NewDocument(template, 0, 0, 0)
    if model is None:
        model = sw.ActiveDoc
    return model


def new_assembly(sw):
    template = sw.GetUserPreferenceStringValue(9)
    model = sw.NewDocument(template, 0, 0, 0)
    if model is None:
        model = sw.ActiveDoc
    return model


def save_model(model, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    model.SaveAs3(str(path), SW_SAVE_CURRENT_VERSION, SW_SAVE_SILENT)
    if not path.exists():
        raise RuntimeError(f"SolidWorks failed to save {path}")


def save_as_if_possible(model, path: Path) -> bool:
    try:
        model.SaveAs3(str(path), SW_SAVE_CURRENT_VERSION, SW_SAVE_SILENT)
        return path.exists()
    except Exception:
        return False


def color_feature(feature, color: Color) -> None:
    feature.SetMaterialPropertyValues2(color.as_variant(), SW_THIS_CONFIGURATION, "")


def rename_feature(feature, name: str):
    if feature is not None:
        feature.Name = name
    return feature


def select_plane(model, plane_name: str) -> None:
    model.ClearSelection2(True)
    if not model.SelectByID(plane_name, "PLANE", 0, 0, 0):
        raise RuntimeError(f"Could not select plane: {plane_name}")


def extrude(model, depth_mm: float, start_offset_mm: float = 0.0, merge: bool = True):
    return model.FeatureManager.FeatureExtrusion2(
        True,
        False,
        False,
        SW_END_BLIND,
        SW_END_BLIND,
        m(depth_mm),
        0.0,
        False,
        False,
        False,
        False,
        0.0,
        0.0,
        False,
        False,
        False,
        False,
        merge,
        True,
        True,
        SW_START_OFFSET if abs(start_offset_mm) > 1e-9 else SW_START_SKETCH_PLANE,
        m(start_offset_mm),
        False,
    )


def add_box(
    model,
    name: str,
    center_mm: tuple[float, float, float],
    size_mm: tuple[float, float, float],
    color: Color,
    merge: bool = True,
):
    cx, cy, cz = center_mm
    sx, sy, sz = size_mm
    select_plane(model, FRONT_PLANE)
    sk = model.SketchManager
    sk.InsertSketch(True)
    sk.CreateCenterRectangle(m(cx), m(cy), 0.0, m(cx + sx / 2), m(cy + sy / 2), 0.0)
    sk.InsertSketch(True)
    feature = extrude(model, sz, cz - sz / 2, merge)
    rename_feature(feature, name)
    color_feature(feature, color)
    return feature


def add_cylinder_z(
    model,
    name: str,
    center_mm: tuple[float, float, float],
    diameter_mm: float,
    height_mm: float,
    color: Color,
    merge: bool = True,
):
    cx, cy, cz = center_mm
    select_plane(model, FRONT_PLANE)
    sk = model.SketchManager
    sk.InsertSketch(True)
    model.CreateCircleByRadius2(m(cx), m(cy), 0.0, m(diameter_mm / 2))
    sk.InsertSketch(True)
    feature = extrude(model, height_mm, cz - height_mm / 2, merge)
    rename_feature(feature, name)
    color_feature(feature, color)
    return feature


def add_cylinder_y(
    model,
    name: str,
    center_mm: tuple[float, float, float],
    diameter_mm: float,
    depth_mm: float,
    color: Color,
    merge: bool = True,
):
    cx, cy, cz = center_mm
    select_plane(model, TOP_PLANE)
    sk = model.SketchManager
    sk.InsertSketch(True)
    model.CreateCircleByRadius2(m(cx), 0.0, m(cz), m(diameter_mm / 2))
    sk.InsertSketch(True)
    feature = extrude(model, depth_mm, cy - depth_mm / 2, merge)
    rename_feature(feature, name)
    color_feature(feature, color)
    return feature


def add_label_plate(
    model,
    name: str,
    center_mm: tuple[float, float, float],
    size_mm: tuple[float, float, float],
    label: str,
):
    add_box(model, f"{name} label plate - {label}", center_mm, size_mm, COLORS["label"], False)


def create_shell_part(sw) -> Path:
    model = new_part(sw)
    # Local origin is the geometric center of the complete 100 x 90 x 70 mm body.
    add_box(model, "bottom plate - 100 x 90 x 3 mm", (0, 0, -33.5), (100, 90, 3), COLORS["shell"], False)
    add_box(model, "back wall - 3 mm", (0, 43.5, 0), (100, 3, 70), COLORS["shell"], False)
    add_box(model, "left side wall - 3 mm", (-48.5, 0, 0), (3, 84, 70), COLORS["shell"], False)
    add_box(model, "right side wall - 3 mm", (48.5, 0, 0), (3, 84, 70), COLORS["shell"], False)
    add_box(model, "front wall lower frame below HC-SR04 window", (0, -43.5, -21), (100, 3, 28), COLORS["shell"], False)
    add_box(model, "front wall upper frame above HC-SR04 window", (0, -43.5, 23), (100, 3, 24), COLORS["shell"], False)
    add_box(model, "front wall left frame", (-36.5, -43.5, 2), (27, 3, 18), COLORS["shell"], False)
    add_box(model, "front wall right frame", (36.5, -43.5, 2), (27, 3, 18), COLORS["shell"], False)
    add_box(model, "transparent top lid - removable", (0, 0, 33.5), (100, 90, 3), COLORS["shell"], False)
    add_box(model, "servo support platform - 36 x 28 x 4 mm", (0, 0, 8), (36, 28, 4), COLORS["mount"], False)
    add_box(model, "battery tray base - 60 x 40 mm", (0, 4, -26), (64, 44, 2), COLORS["mount"], False)

    for i, (x, y) in enumerate([(-32, -24), (32, -24), (-32, 24), (32, 24)], start=1):
        add_cylinder_z(
            model,
            f"PCB standoff {i} - M3 clearance marker",
            (x, y, -26),
            6,
            14,
            COLORS["mount"],
            False,
        )

    add_label_plate(model, "case", (-30, 48, 23), (38, 2, 9), "CASE 100x90x70")
    model.ViewZoomtofit2()
    path = PARTS_DIR / "MiniPal_case_shell.SLDPRT"
    save_model(model, path)
    return path


def create_hcsr04_part(sw) -> Path:
    model = new_part(sw)
    add_box(model, "HC-SR04 PCB - 45 x 20 mm", (0, 0, 0), (45, 2.4, 20), COLORS["sensor_board"], False)
    add_cylinder_y(model, "left ultrasonic transducer eye - dia 16 mm", (-12.5, -5.2, 0), 16, 8, COLORS["sensor_eye"], False)
    add_cylinder_y(model, "right ultrasonic transducer eye - dia 16 mm", (12.5, -5.2, 0), 16, 8, COLORS["sensor_eye"], False)
    add_box(model, "4 pin header block", (0, 2.0, -8.3), (18, 3.2, 3), COLORS["pin"], False)
    add_label_plate(model, "sensor", (0, -9.8, 13.5), (34, 1.2, 5), "HC-SR04 45x20")
    model.ViewZoomtofit2()
    path = PARTS_DIR / "MiniPal_HC_SR04_sensor.SLDPRT"
    save_model(model, path)
    return path


def create_servo_part(sw) -> Path:
    model = new_part(sw)
    add_box(model, "SG90 body - approx 22.2 x 11.8 x 31 mm", (0, 0, 0), (22.2, 11.8, 31), COLORS["servo"], False)
    add_box(model, "SG90 mounting ear left", (-15.5, 0, -3), (8.8, 11.8, 2.6), COLORS["servo"], False)
    add_box(model, "SG90 mounting ear right", (15.5, 0, -3), (8.8, 11.8, 2.6), COLORS["servo"], False)
    add_cylinder_z(model, "servo spline hub", (0, 0, 18.5), 7.0, 3.0, COLORS["servo_horn"], False)
    add_cylinder_z(model, "servo horn center", (0, 0, 22.0), 14.0, 1.8, COLORS["servo_horn"], False)
    add_box(model, "servo horn arm", (0, 0, 23.2), (34, 4, 1.8), COLORS["servo_horn"], False)
    add_label_plate(model, "servo", (0, 8.5, 4), (26, 1.2, 6), "SG90")
    model.ViewZoomtofit2()
    path = PARTS_DIR / "MiniPal_SG90_servo.SLDPRT"
    save_model(model, path)
    return path


def create_esp32_part(sw) -> Path:
    model = new_part(sw)
    add_box(model, "ESP32 DevKit PCB - approx 55 x 28 mm", (0, 0, 0), (55, 28, 2.0), COLORS["esp32"], False)
    add_box(model, "ESP-WROOM shield can", (1, 0, 3.5), (18, 20, 3.0), COLORS["module"], False)
    add_box(model, "micro USB connector", (31, 0, 2.5), (7, 9, 5.0), COLORS["module"], False)
    add_box(model, "reset / boot button pair", (-23, 0, 3.0), (5, 18, 2.5), COLORS["button"], False)
    add_box(model, "left pin header row", (0, -15.5, 2.6), (52, 2.2, 3.2), COLORS["pin"], False)
    add_box(model, "right pin header row", (0, 15.5, 2.6), (52, 2.2, 3.2), COLORS["pin"], False)
    add_label_plate(model, "esp32", (0, 20, 5), (38, 1.2, 6), "ESP32 55x28")
    model.ViewZoomtofit2()
    path = PARTS_DIR / "MiniPal_ESP32_devkit.SLDPRT"
    save_model(model, path)
    return path


def create_power_part(sw) -> Path:
    model = new_part(sw)
    add_box(model, "5V battery / power bank envelope - 60 x 40 x 12 mm", (0, 0, 0), (60, 40, 12), COLORS["battery"], False)
    add_box(model, "USB power cable clearance marker", (34, 0, 0), (8, 9, 6), COLORS["module"], False)
    add_label_plate(model, "power", (0, 24, 2), (42, 1.2, 6), "5V POWER")
    model.ViewZoomtofit2()
    path = PARTS_DIR / "MiniPal_5V_power_pack.SLDPRT"
    save_model(model, path)
    return path


def create_button_part(sw) -> Path:
    model = new_part(sw)
    add_cylinder_z(model, "top wake button cap - dia 16 mm", (0, 0, 0), 16, 6, COLORS["button"], False)
    add_cylinder_z(model, "button threaded body / hole marker - dia 12 mm", (0, 0, -5), 12, 8, COLORS["module"], False)
    add_label_plate(model, "button", (0, 11, 2), (28, 1.2, 5), "WAKE BTN")
    model.ViewZoomtofit2()
    path = PARTS_DIR / "MiniPal_top_button.SLDPRT"
    save_model(model, path)
    return path


def create_led_part(sw) -> Path:
    model = new_part(sw)
    add_box(model, "WS2812 RGB LED board - 12 x 12 mm", (0, 0, 0), (12, 12, 1.6), COLORS["module"], False)
    add_cylinder_z(model, "RGB LED diffuser", (0, 0, 2.4), 8, 2.4, COLORS["led"], False)
    add_label_plate(model, "led", (0, 9, 2), (25, 1.2, 5), "WS2812")
    model.ViewZoomtofit2()
    path = PARTS_DIR / "MiniPal_WS2812_LED.SLDPRT"
    save_model(model, path)
    return path


def create_buzzer_part(sw) -> Path:
    model = new_part(sw)
    add_cylinder_z(model, "active buzzer - dia 12 x 9 mm", (0, 0, 0), 12, 9, COLORS["buzzer"], False)
    add_cylinder_z(model, "sound outlet marker", (0, 0, 5.0), 5, 0.8, COLORS["shell_edge"], False)
    add_label_plate(model, "buzzer", (0, 9, 2), (28, 1.2, 5), "BUZZER")
    model.ViewZoomtofit2()
    path = PARTS_DIR / "MiniPal_buzzer.SLDPRT"
    save_model(model, path)
    return path


def create_label_part(sw) -> Path:
    model = new_part(sw)
    add_box(model, "overall X dimension marker - body length 100 mm", (0, -58, 0), (100, 1, 1), COLORS["label"], False)
    add_box(model, "overall Y dimension marker - body width 90 mm", (58, 0, 0), (1, 90, 1), COLORS["label"], False)
    add_box(model, "overall Z dimension marker - body height 70 mm", (58, 50, 35), (1, 1, 70), COLORS["label"], False)
    add_box(model, "front arrow / sensor face marker", (0, -51, 7), (46, 2, 4), COLORS["label"], False)
    add_label_plate(model, "overall", (-25, -61, 3), (45, 1.2, 6), "100mm")
    add_label_plate(model, "overall", (61, -25, 3), (1.2, 45, 6), "90mm")
    add_label_plate(model, "overall", (61, 52, 35), (1.2, 6, 30), "70mm")
    model.ViewZoomtofit2()
    path = PARTS_DIR / "MiniPal_dimension_markers.SLDPRT"
    save_model(model, path)
    return path


def create_case_details_part(sw) -> Path:
    model = new_part(sw)
    add_box(model, "front face trim around HC-SR04 eye window", (0, -51, 37), (62, 2.2, 22), COLORS["trim"], False)
    add_box(model, "top translucent status light strip", (0, -20, 72.2), (42, 10, 2.4), COLORS["clear"], False)
    add_box(model, "left cheek decorative insert", (-36, -51.5, 30), (12, 2.0, 8), COLORS["trim"], False)
    add_box(model, "right cheek decorative insert", (36, -51.5, 30), (12, 2.0, 8), COLORS["trim"], False)

    for i, (x, y) in enumerate([(-35, -30), (35, -30), (-35, 30), (35, 30)], start=1):
        add_cylinder_z(model, f"rubber foot {i}", (x, y, -2), 12, 4, COLORS["rubber"], False)

    model.ViewZoomtofit2()
    path = PARTS_DIR / "MiniPal_case_details_feet_trim.SLDPRT"
    save_model(model, path)
    return path


def create_sim_robot_appearance_part(sw) -> Path:
    model = new_part(sw)
    # Visual model matching simulation/index.html: head, neck, rounded-like body,
    # ultrasonic "eyes", LED ring, board window, and speaker grille.
    add_box(model, "simulation style body - rounded body envelope", (0, 48, 0), (100, 90, 42), COLORS["sim_body"], False)
    add_box(model, "body lower shadow inset", (10, 18, -22.5), (72, 14, 2.6), COLORS["sim_shadow"], False)
    add_box(model, "body right inner shadow", (39, 48, -22.5), (12, 78, 2.6), COLORS["sim_shadow"], False)

    add_cylinder_z(model, "LED ring outer - status light", (0, 70, -24.5), 27, 3.5, COLORS["sim_led_blue"], False)
    add_cylinder_z(model, "LED ring hollow center marker", (0, 70, -26.0), 15, 3.8, COLORS["sim_body"], False)

    add_box(model, "ESP32 state display window", (0, 42, -25.0), (68, 30, 3.0), COLORS["sim_window"], False)
    add_box(model, "window text block - ESP32", (-18, 46, -27.0), (24, 4, 1.2), COLORS["module"], False)
    add_box(model, "window text block - STATE", (18, 36, -27.0), (30, 4, 1.2), COLORS["module"], False)

    for i, x in enumerate([-24, -15, -6, 3, 12, 21], start=1):
        add_box(model, f"speaker grille slot {i}", (x, 13, -27.0), (5, 3, 1.8), COLORS["module"], False)

    add_box(model, "neck block", (0, 101, 0), (28, 18, 34), COLORS["sim_shadow"], False)
    add_box(model, "head shell - simulation face", (0, 136, 0), (84, 58, 40), COLORS["sim_head"], False)
    add_box(model, "head lower lip / face slot", (0, 119, -24.8), (38, 5, 3.0), COLORS["module"], False)
    add_box(model, "head side shadow", (36, 136, -21.0), (8, 48, 2.2), COLORS["sim_shadow"], False)
    add_box(model, "head bottom shadow", (0, 111, -21.0), (72, 7, 2.2), COLORS["sim_shadow"], False)

    for side, x in [("left", -22), ("right", 22)]:
        add_cylinder_z(model, f"{side} sensor eye outer dark ring", (x, 139, -25.2), 22, 3.5, COLORS["module"], False)
        add_cylinder_z(model, f"{side} sensor eye silver ring", (x, 139, -27.0), 17, 3.5, COLORS["sim_eye_ring"], False)
        add_cylinder_z(model, f"{side} sensor eye blue center", (x, 139, -28.8), 11, 3.0, COLORS["sim_eye_blue"], False)
        add_cylinder_z(model, f"{side} eye highlight", (x - 3.2, 142.6, -30.4), 3.2, 1.2, COLORS["sim_head"], False)

    add_cylinder_y(model, "top wake button like simulator control", (0, 170, 0), 15, 7, COLORS["button"], False)
    add_box(model, "front HC-SR04 face plate marker", (0, 139, -31.0), (58, 2, 2.0), COLORS["sensor_board"], False)
    add_label_plate(model, "appearance", (-33, -2, -24), (44, 1.2, 6), "MiniPal")

    model.ViewZoomtofit2()
    path = PARTS_DIR / "MiniPal_simulation_style_robot.SLDPRT"
    save_model(model, path)
    return path


def create_wire_harness_part(sw) -> Path:
    model = new_part(sw)
    add_box(model, "sensor cable: HC-SR04 to ESP32", (0, -26, 37), (3, 42, 2), COLORS["wire"], False)
    add_box(model, "servo PWM cable: SG90 to ESP32", (-18, 1, 47), (3, 35, 2), COLORS["wire"], False)
    add_box(model, "LED data cable: WS2812 to ESP32", (-21, -13, 36), (18, 2, 2), COLORS["wire"], False)
    add_box(model, "buzzer signal cable: buzzer to ESP32", (22, -13, 34), (18, 2, 2), COLORS["wire"], False)
    add_box(model, "5V power leads: battery to main rail", (0, 6, 18), (5, 3, 12), COLORS["wire"], False)
    add_box(model, "USB side exit clearance marker", (50.5, 6, 24), (2, 12, 8), COLORS["module"], False)
    model.ViewZoomtofit2()
    path = PARTS_DIR / "MiniPal_wire_harness_and_ports.SLDPRT"
    save_model(model, path)
    return path


def close_doc(sw, path: Path) -> None:
    try:
        sw.CloseDoc(path.name)
    except Exception:
        pass


def open_doc(sw, path: Path, doc_type: int):
    return sw.OpenDoc(str(path), doc_type)


def activate_doc(sw, path: Path, doc_type: int):
    doc = None
    try:
        doc = sw.ActivateDoc(path.name)
    except Exception:
        pass
    if doc is None:
        doc = open_doc(sw, path, doc_type)
    return sw.ActiveDoc if sw.ActiveDoc is not None else doc


def create_assembly(sw, name: str, components: Iterable[tuple[Path, tuple[float, float, float]]]) -> Path:
    model = new_assembly(sw)
    asm = model
    assembly_title = model.GetTitle
    for path, pos_mm in components:
        doc_type = SW_DOC_PART if path.suffix.lower() == ".sldprt" else SW_DOC_ASSEMBLY
        open_doc(sw, path, doc_type)
        sw.ActivateDoc(assembly_title)
        x, y, z = pos_mm
        comp = asm.AddComponent5(
            str(path),
            SW_ADD_CURRENT_SELECTED_CONFIG,
            "",
            False,
            "",
            m(x),
            m(y),
            m(z),
        )
        if comp is None:
            raise RuntimeError(f"Failed to add component: {path}")
    try:
        model.ShowNamedView2("*Isometric", 7)
    except Exception:
        pass
    model.ViewZoomtofit2()
    path = ASSEMBLY_DIR / f"{name}.SLDASM"
    save_model(model, path)
    return path


def export_png_view(model, path: Path, view_name: str, view_id: int) -> Path | None:
    try:
        model.ShowNamedView2(view_name, view_id)
    except Exception:
        pass
    try:
        model.ViewZoomtofit2()
    except Exception:
        pass
    if save_as_if_possible(model, path):
        return path
    return None


def write_readme(paths: dict[str, Path], exports: dict[str, Path | None]) -> None:
    readme = PROJECT_DIR / "README.md"
    lines = [
        "# MiniPal SolidWorks Model",
        "",
        "Generated by `mechanical/scripts/build_minipal_solidworks.py`.",
        "",
        "## Main files",
        "",
        f"- Top assembly: `{paths['top_assembly'].relative_to(PROJECT_DIR)}`",
        f"- Internal module layout assembly: `{paths['module_layout_assembly'].relative_to(PROJECT_DIR)}`",
        f"- Exploded layout assembly: `{paths['exploded_assembly'].relative_to(PROJECT_DIR)}`",
        f"- Electronics sub-assembly: `{paths['electronics_assembly'].relative_to(PROJECT_DIR)}`",
        f"- Motion sub-assembly: `{paths['motion_assembly'].relative_to(PROJECT_DIR)}`",
        f"- Parts folder: `parts/`",
        f"- Exports folder: `exports/`",
        "",
        "## Design envelope",
        "",
        "- Main assembly matches the browser simulator silhouette: separate head, neck, body, HC-SR04 eyes, LED ring, ESP32 window, and speaker slot.",
        "- Mechanical case envelope retained for module layout: `100 x 90 x 70 mm`",
        "- Wall thickness marker: `3 mm`",
        "- Front module: HC-SR04 ultrasonic sensor as robot eyes",
        "- Top module: wake button",
        "- Upper layer: SG90 servo and head-motion platform",
        "- Middle layer: ESP32 DevKit",
        "- Lower layer: 5V power / battery tray",
        "- Added details: rubber feet, front trim, translucent status strip, simplified wire harness, USB clearance marker",
        "",
        "## Simplified module dimensions",
        "",
        "- HC-SR04: `45 x 20 x 15 mm` reference envelope, modeled as board plus two transducer eyes.",
        "- SG90: `22.2 x 11.8 x 31 mm` reference envelope, modeled with ears and horn.",
        "- ESP32 DevKit: `55 x 28 mm` common board footprint envelope; exact clones vary.",
        "- WS2812 LED and buzzer are simplified module blocks for layout clarity.",
        "",
        "## Reference sources used",
        "",
        "- Otto DIY open-source robot was used as a real-world reference for using an ultrasonic sensor as a face/eyes module and SG90-class servos in a 3D-printed educational robot: https://www.ottodiy.com/",
        "- Otto DIY GitHub BOM/context confirms a 3D-printable robot using HC-SR04 and SG90 parts: https://github.com/Open-Hardware-Leaders/OttoDIY",
        "- HC-SR04 dimensions reference: https://www.digikey.com/en/htmldatasheets/production/3822706/0/0/1/hc-sr04.html",
        "- SG90 dimensions reference: https://datasheet4u.com/datasheets/Tower-Pro/SG90/791970",
        "- ESP32 DevKit reference footprints vary; common DevKitC/DevKit V1 references include Espressif/Adafruit/DOIT-style sizes around 51-55 mm length and 23-28 mm width: https://docs.espressif.com/projects/esp-idf/en/v4.4/esp32/hw-reference/esp32/get-started-devkitc.html and https://www.adafruit.com/product/3269",
        "",
        "## Exports",
        "",
    ]
    for key, path in exports.items():
        if path:
            lines.append(f"- {key}: `{path.relative_to(PROJECT_DIR)}`")
        else:
            lines.append(f"- {key}: export skipped by local SolidWorks settings")
    lines.append("")
    readme.write_text("\n".join(lines), encoding="utf-8")


def write_finished_readme(top: Path, sim_part: Path, exports: dict[str, Path | None]) -> None:
    readme = PROJECT_DIR / "README.md"
    lines = [
        "# MiniPal SolidWorks Finished Model",
        "",
        "Generated by `mechanical/scripts/build_minipal_solidworks.py --appearance-only`.",
        "",
        "## Main files",
        "",
        f"- Finished robot assembly: `{top.relative_to(PROJECT_DIR)}`",
        f"- Finished robot visual part: `{sim_part.relative_to(PROJECT_DIR)}`",
        "- Simplified module parts: `parts/`",
        "- Exports folder: `exports/`",
        "",
        "## What this model represents",
        "",
        "- The finished assembly is intentionally integrated, matching the browser simulator silhouette.",
        "- It includes a separate head, neck, rounded-style body, HC-SR04 double eyes, face slot, LED ring, ESP32 display window, speaker grille, and top wake button.",
        "- Internal module files are retained in `parts/` as size references, but they are not exploded around the final model.",
        "",
        "## Key dimensions",
        "",
        "- Project mechanical case reference: `100 x 90 x 70 mm`.",
        "- HC-SR04 reference envelope: `45 x 20 x 15 mm`.",
        "- SG90 reference envelope: `22.2 x 11.8 x 31 mm`.",
        "- ESP32 DevKit reference envelope: about `55 x 28 mm`; exact clone sizes vary.",
        "",
        "## References",
        "",
        "- Otto DIY real-world reference for ultrasonic eyes and SG90-class servos: https://www.ottodiy.com/",
        "- HC-SR04 dimensions reference: https://www.digikey.com/en/htmldatasheets/production/3822706/0/0/1/hc-sr04.html",
        "- SG90 dimensions reference: https://datasheet4u.com/datasheets/Tower-Pro/SG90/791970",
        "",
        "## Exports",
        "",
    ]
    for key, path in exports.items():
        if path:
            lines.append(f"- {key}: `{path.relative_to(PROJECT_DIR)}`")
        else:
            lines.append(f"- {key}: export skipped by local SolidWorks settings")
    lines.append("")
    readme.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    assemble_only = "--assemble-only" in sys.argv
    appearance_only = "--appearance-only" in sys.argv
    sw = connect_solidworks()

    # Remove temporary scratch documents created while testing the automation,
    # but keep SolidWorks open for the final result.
    try:
        sw.CloseAllDocuments(True)
    except Exception:
        pass

    ensure_dirs(clean=not assemble_only and not appearance_only)

    part_paths = {
        "shell": PARTS_DIR / "MiniPal_case_shell.SLDPRT",
        "sensor": PARTS_DIR / "MiniPal_HC_SR04_sensor.SLDPRT",
        "servo": PARTS_DIR / "MiniPal_SG90_servo.SLDPRT",
        "esp32": PARTS_DIR / "MiniPal_ESP32_devkit.SLDPRT",
        "power": PARTS_DIR / "MiniPal_5V_power_pack.SLDPRT",
        "button": PARTS_DIR / "MiniPal_top_button.SLDPRT",
        "led": PARTS_DIR / "MiniPal_WS2812_LED.SLDPRT",
        "buzzer": PARTS_DIR / "MiniPal_buzzer.SLDPRT",
        "labels": PARTS_DIR / "MiniPal_dimension_markers.SLDPRT",
        "case_details": PARTS_DIR / "MiniPal_case_details_feet_trim.SLDPRT",
        "sim_robot": PARTS_DIR / "MiniPal_simulation_style_robot.SLDPRT",
        "wires": PARTS_DIR / "MiniPal_wire_harness_and_ports.SLDPRT",
    }

    if assemble_only or appearance_only:
        missing = [str(path) for path in part_paths.values() if not path.exists()]
        if missing:
            raise FileNotFoundError("Missing part files for --assemble-only:\n" + "\n".join(missing))
    else:
        creators = {
            "shell": create_shell_part,
            "sensor": create_hcsr04_part,
            "servo": create_servo_part,
            "esp32": create_esp32_part,
            "power": create_power_part,
            "button": create_button_part,
            "led": create_led_part,
            "buzzer": create_buzzer_part,
            "labels": create_label_part,
            "case_details": create_case_details_part,
            "sim_robot": create_sim_robot_appearance_part,
            "wires": create_wire_harness_part,
        }
        for key, creator in creators.items():
            part_paths[key] = creator(sw)
        for path in part_paths.values():
            close_doc(sw, path)

    if appearance_only:
        top = create_assembly(
            sw,
            "MiniPal_main_assembly",
            [
                (part_paths["sim_robot"], (0, 0, 0)),
            ],
        )
        top_model = activate_doc(sw, top, SW_DOC_ASSEMBLY)
        exports: dict[str, Path | None] = {
            "STEP": None,
            "PNG preview - isometric": None,
            "PNG preview - front": None,
            "PNG preview - top layout": None,
        }
        iso_png = export_png_view(top_model, EXPORT_DIR / "MiniPal_main_assembly_isometric.png", "*Isometric", 7)
        if iso_png:
            exports["PNG preview - isometric"] = iso_png
        front_png = export_png_view(top_model, EXPORT_DIR / "MiniPal_main_assembly_front.png", "*Front", 1)
        if front_png:
            exports["PNG preview - front"] = front_png
        top_png = export_png_view(top_model, EXPORT_DIR / "MiniPal_main_assembly_top_layout.png", "*Top", 5)
        if top_png:
            exports["PNG preview - top layout"] = top_png
        step_path = EXPORT_DIR / "MiniPal_main_assembly.step"
        top_model = activate_doc(sw, top, SW_DOC_ASSEMBLY)
        if save_as_if_possible(top_model, step_path):
            exports["STEP"] = step_path
        write_finished_readme(top, part_paths["sim_robot"], exports)
        print(f"Created MiniPal finished SolidWorks model: {PROJECT_DIR}")
        print(f"Top assembly: {top}")
        if exports["STEP"]:
            print(f"STEP export: {exports['STEP']}")
        if exports["PNG preview - isometric"]:
            print(f"PNG preview: {exports['PNG preview - isometric']}")
        return 0

    electronics = create_assembly(
        sw,
        "MiniPal_electronics_subassembly",
        [
            (part_paths["esp32"], (0, 6, 25)),
            (part_paths["power"], (0, 6, 11)),
            (part_paths["sensor"], (0, -48.5, 37)),
            (part_paths["led"], (-30, -18, 36)),
            (part_paths["buzzer"], (31, -18, 32)),
            (part_paths["wires"], (0, 0, 0)),
        ],
    )
    close_doc(sw, electronics)

    motion = create_assembly(
        sw,
        "MiniPal_motion_subassembly",
        [
            (part_paths["servo"], (0, 0, 51)),
            (part_paths["button"], (0, 0, 73)),
        ],
    )
    close_doc(sw, motion)

    module_layout = create_assembly(
        sw,
        "MiniPal_internal_module_layout_assembly",
        [
            (part_paths["shell"], (0, 0, 35)),
            (part_paths["case_details"], (0, 0, 0)),
            (electronics, (0, 0, 0)),
            (motion, (0, 0, 0)),
            (part_paths["labels"], (0, 0, 0)),
        ],
    )
    close_doc(sw, module_layout)

    top = create_assembly(
        sw,
        "MiniPal_main_assembly",
        [
            (part_paths["sim_robot"], (0, 0, 0)),
        ],
    )

    exports: dict[str, Path | None] = {
        "STEP": None,
        "PNG preview - isometric": None,
        "PNG preview - front": None,
        "PNG preview - top layout": None,
    }
    top_model = activate_doc(sw, top, SW_DOC_ASSEMBLY)
    iso_png = export_png_view(top_model, EXPORT_DIR / "MiniPal_main_assembly_isometric.png", "*Isometric", 7)
    if iso_png:
        exports["PNG preview - isometric"] = iso_png
    front_png = export_png_view(top_model, EXPORT_DIR / "MiniPal_main_assembly_front.png", "*Front", 1)
    if front_png:
        exports["PNG preview - front"] = front_png
    top_png = export_png_view(top_model, EXPORT_DIR / "MiniPal_main_assembly_top_layout.png", "*Top", 5)
    if top_png:
        exports["PNG preview - top layout"] = top_png

    step_path = EXPORT_DIR / "MiniPal_main_assembly.step"
    top_model = activate_doc(sw, top, SW_DOC_ASSEMBLY)
    if save_as_if_possible(top_model, step_path):
        exports["STEP"] = step_path

    exploded = create_assembly(
        sw,
        "MiniPal_exploded_layout_assembly",
        [
            (part_paths["shell"], (0, 0, 35)),
            (part_paths["case_details"], (0, 0, 0)),
            (electronics, (135, 0, 0)),
            (motion, (-105, 0, 0)),
            (part_paths["labels"], (0, 0, 0)),
        ],
    )
    exploded_model = activate_doc(sw, exploded, SW_DOC_ASSEMBLY)
    exploded_png = export_png_view(
        exploded_model,
        EXPORT_DIR / "MiniPal_exploded_layout_isometric.png",
        "*Isometric",
        7,
    )
    if exploded_png:
        exports["PNG preview - exploded layout"] = exploded_png

    try:
        top_model = activate_doc(sw, top, SW_DOC_ASSEMBLY)
        top_model.ShowNamedView2("*Isometric", 7)
        top_model.ViewZoomtofit2()
    except Exception:
        pass

    paths = {
        "top_assembly": top,
        "module_layout_assembly": module_layout,
        "exploded_assembly": exploded,
        "electronics_assembly": electronics,
        "motion_assembly": motion,
    }
    write_readme(paths, exports)

    print(f"Created MiniPal SolidWorks project: {PROJECT_DIR}")
    print(f"Top assembly: {top}")
    if exports["STEP"]:
        print(f"STEP export: {exports['STEP']}")
    if exports["PNG preview - isometric"]:
        print(f"PNG preview: {exports['PNG preview - isometric']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
